name: Run k6 test in fargate

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/k6-test-repo:latest-k6-amd64

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Fargate task in us-east-1
      run: |
        aws ecs register-task-definition --cli-input-json file://task-definition.json
        aws ecs run-task --cluster my-cluster --task-definition my-k6-test --count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-0abcdef1234567890],securityGroups=[sg-0abcdef1234567890],assignPublicIp=ENABLED}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Run Fargate task in us-east-2
      run: |
        aws ecs register-task-definition --cli-input-json file://task-definition.json
        aws ecs run-task --cluster my-cluster --task-definition my-k6-test --count 1 --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[subnet-0abcdef1234567890],securityGroups=[sg-0abcdef1234567890],assignPublicIp=ENABLED}"
