name: K6 Load Test on AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  load_test_us_east_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR (us-east-1)
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381491835787.dkr.ecr.us-east-1.amazonaws.com/k6-test-repo

      - name: Run k6 Load Test in us-east-1
        run: |
          aws ecs run-task --cluster k6-cluster --task-definition arn:aws:ecs:us-east-1:381491835787:task-definition/k6-fargate-task-definition:3 --launch-type FARGATE --region us-east-1

  load_test_us_east_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR (us-east-2)
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 381491835787.dkr.ecr.us-east-2.amazonaws.com/k6-test-repo

      - name: Run k6 Load Test in us-east-2
        run: |
          aws ecs run-task --cluster k6-cluster1 --task-definition arn:aws:ecs:us-east-2:381491835787:task-definition/k6-fargate-task-definition2:1 --launch-type FARGATE --region us-east-2
